version: "3.3"

networks:
  mnetwork:
    driver: bridge

services:

  echoservice:
    build:
      context: ./
      dockerfile: echoservice.Dockerfile
    networks:
      - mnetwork
    ports:
      - 5001:5001
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:attachme-agent.jar=port:7857,host:172.17.0.1 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5001"
    entrypoint: java EchoService 8081

  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    networks:
      - mnetwork
    depends_on:
      - echoservice
    ports:
      - 5002:5002
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:attachme-agent.jar=port:7857,host:172.17.0.1 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5002"
    entrypoint: java Client echoservice 8081 HelloWorld