package com.attachme.plugin;

import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.SettingsEditor;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

public class AttachmeSettingsEditor extends SettingsEditor<AttachmeRunConfig> {

  private JPanel root;

  private JTextField portField;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    root = new JPanel();
    root.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
    final Spacer spacer1 = new Spacer();
    root.add(spacer1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("Listen on port:");
    root.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    portField = new JTextField();
    root.add(portField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return root;
  }

  @Override
  protected void resetEditorFrom(@NotNull AttachmeRunConfig s) {
    portField.setText(s.getPort() + "");
  }

  @Override
  protected void applyEditorTo(@NotNull AttachmeRunConfig s) throws ConfigurationException {
    int port;
    try {
      port = Integer.parseInt(portField.getText());
      if (port <= 0) {
        throw new ConfigurationException("Port has to be greater than 0");
      }
    } catch (NumberFormatException e) {
      throw new ConfigurationException("Port has to be a number");
    }
    s.setPort(port);
  }

  @NotNull
  @Override
  protected JComponent createEditor() {
    return $$$getRootComponent$$$();
  }
}
